<Project Sdk="Microsoft.NET.Sdk.Web">

  <!-- TargetFramework, Nullable e ImplicitUsings vienen de Directory.Build.props -->

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Biblioteca.Contracts\Biblioteca.Contracts.csproj" />
  </ItemGroup>

</Project>
